### ISSUE TITLE
Error: "cannot open file ...."

### ISSUE THREAD

**Issue by jeetsukumaran** [radamsRHA/PSTDistanceR#1]
Hi!

I've got everything set up and installed.
When trying to run the example, I get the following error:

```
Loading required package: ape
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
Calls: Compute.Probabilistic.SpeciesTree.Distances -> RunHybridCoal -> write.tree -> cat -> file
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file './PSTD_2023-08-08/SpeciesTreeModel_Model1_2023-08-08//SpeciesTreeModel_Model1.tree': No such file or directory
Execution halted
```

The directories seem to be created OK but are empty:

```
$ tree PSTD_2023-08-08/SpeciesTreeModel_Model1_2023-08-08/
PSTD_2023-08-08/SpeciesTreeModel_Model1_2023-08-08/

0 directories, 0 files
```

It seems like the underlying script (``Compute.Probabilistic.SpeciesTree.Distances.R``) or something it calls is trying to open a tree file that's not found. Am I supposed to create this myself?

**Comment by radamsRHA** [comment]
Hi!

Thanks for reaching out!

Hmm... That is a strange result. I will dig deeper and see what I find. I just double checked on MacOS and Ubuntu, and I am able to recreate the example results using the following commands:

```
library(phangorn);library(PSTDistanceR)

handle.SpeciesTree.A <- read.tree(text = "(((A:1,B:1):1,C:2):1,D:3);")
handle.SpeciesTree.B <- read.tree(text = "(((A:1,C:1):1,B:2):1,D:3);")

Compute.Probabilistic.SpeciesTree.Distances(handle.SpeciesTree.Model1 = handle.SpeciesTree.A, 
                                            handle.SpeciesTree.Model2 = handle.SpeciesTree.B, 
                                            string.PathParentDir = '/home/adamsrh/TEST/', 
                                            string.PathHybridCoal = '/home/adamsrh/TEST/hybrid-coal-v0.2.1-beta/hybrid-coal')
```

Could you share the command when you get the chance?

Thanks again!
Rich

**Comment by jeetsukumaran** [comment]
Thanks! That helped fix the problem. The issue was that I was using relative paths:

```
string.PathParentDir = '.'
```

Using the full absolute path worked perfectly. 

Appreciate your time and effort on this :)
